### ISSUE TITLE
ReferenceError: require is not defined 

### ISSUE THREAD

**Issue by olenhad** [bodil/cljs-noderepl#2]
Hey, I got the following error upon starting:

``` javascript
"Error evaluating:" (set! cljs.core/*print-fn* (.-print (js/require "util"))) :as "cljs.core._STAR_print_fn_STAR_ = require(\"util\").print;\n"
ReferenceError: require is not defined
    at <cljs repl>:1:34
    at Socket.<anonymous> (eval at <anonymous> (eval at <anonymous> (eval:1:82)))
    at Socket.emit (events.js:67:17)
    at Pipe.onread (net.js:347:14)
```

Do I need to add specific cljsbuild directives. I suspect thats the issue. Here's my project.clj for reference sake:

``` clojure
(defproject noderepl "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.4.0"]
                 ]
  :plugins [[org.bodil/lein-noderepl "0.1.5"]])
```

**Comment by bodil** [comment]
What version of Node are you using?

**Comment by olenhad** [comment]
Didn't work with 0.6.12, 0.6.17
Made nvm use 0.8.19 and it works fine. 
My bad I guess. You might want to add that to the readme though.
